#!/bin/bash
set -e # fail on any error

. /usr/share/debconf/confmodule

set -u # treat unset variables as errors

# ======[ Trap Errors ]======#
set -E # let shell functions inherit ERR trap

# Trap non-normal exit signals:
# 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
trap err_handler 1 2 3 15 ERR
function err_handler {
local exit_status=${1:-$?}
logger -s -p "syslog.err" -t "lexnew.deb" "lexnew.deb script '$0' error code $exit_status (line $BASH_LINENO: '$BASH_COMMAND')"
exit $exit_status
}

echo "POSTRM-script"

#echo "deleting /etc/profile.d/lexnew_profile.sh"
#rm /etc/profile.d/lexnew_profile.sh &>/dev/null || true

CURUSER=`who | grep ":0" | head -n 1 | awk '{print($1)}'`
if [ ! -z "$CURUSER" ];
then
	echo "CURUSER=$CURUSER"
	if [ -e /home/"$CURUSER"/.lexnew ]; then
		echo "exists .lexnew"
		rm -r /home/"$CURUSER"/.lexnew
	fi
	if [ -L /home/"$CURUSER"/Desktop/LexNew ]; then
		echo "exists link"
		rm /home/"$CURUSER"/Desktop/LexNew
	fi
fi
if [ "$1" == "purge" ] #&& [ -e /usr/share/debconf/confmodule ] ; then
then
	#echo "invoking db_purge"
	db_purge
fi

echo "exit POSTRM-script"

exit 0
